* coronium

#+begin_quote
*coronium*: a hypothetical chemical element thought to have been detected in the
solar corona whose spectrum showed a number of lines later identified as
belonging to iron, nickel, and other elements highly ionized at the extreme
solar temperatures.
#+end_quote

Coronium is the ghidra disassembler + decompiler in library form. Made suitable for use in c++ projects.
Usage is as easy as =g++ <your-code>.cpp $(pkg-config --cflags --libs coronium) -o output>=.

** Install
Coronium will install =slgh-compile= (i.e., the sleigh compiler) as well as the
=coronium= header files and =libcoronium.so=. cpu specification files (=.sla=
files) will be installed in =/var/coronium/cpus= (default location).

#+begin_src shell
  mkdir build
  cd build
  cmake ..                             # (alt.) cmake .. -DSLA_LOCATION=<your-directory>
  make -j$(nproc)
  sudo make cpus                       # build and install .sla files.
  sudo make install                    # install headers + lib.
  sudo ldconfig                        # make linker recognize lib on path.
#+end_src

After install you can link to targets with headers such as
#+begin_src c++
  /* main.cpp */
  #include <coronium/coronium.hpp>
  #include <coronium/types.h>
  #include <coronium/loadimage.hh>
  #include <coronium/sleigh.hh>
  #include <coronium/emulate.hh>
  /* ... */  
#+end_src

via the cmdline -- =g++ main.cpp -lcoronium -o main=
