* coronium

#+begin_quote
*coronium*: a hypothetical chemical element thought to have been detected in the
solar corona whose spectrum showed a number of lines later identified as
belonging to iron, nickel, and other elements highly ionized at the extreme
solar temperatures.
#+end_quote

Coronium is the ghidra disassembler + decompiler in library form. Made suitable
for use in c++ projects. Usage is as easy as =g++ <your-code>.cpp $(pkg-config
--cflags --libs coronium) -o output>=. None of the Ghidra source code for the
decompiler has been modified. This project simply enables installation as a
library and defines a convenience header =coronium.hpp= that holds helper
function(s) to simplify interacting with the ghidra library code.

** Install
#+begin_src shell
  mkdir build
  cd build
  cmake ..                             # (alt.) cmake .. -DSLA_LOCATION=<your-directory>
  make -j$(nproc)
  sudo make cpus                       # build and install .sla files.
  sudo make install                    # install headers + lib.
  sudo ldconfig                        # make linker recognize lib on path.
#+end_src

Coronium will install =slgh-compile= (i.e., the sleigh compiler), =coronium=
header files and =libcoronium.so=. The cpu specification files (=.sla= files)
will be installed in =/var/coronium= (default location --can change this during
install).

However, if you decide to change/move the cpu directory, just be sure to set the
environment variable =SLA_DIR= to this new location. That way the macro
=SLA_LOCATION()= will still be able to find cpu definitions. The environment
variable =SLA_DIR= is given precedence over whatever path was decided during the
initial install.

*** NOTE
    when specifying =SLA_DIR=, do not end the path with "/" for example, do
@@html:<pre>@@export SLA_DIR="​/var​/blah"@@html:</pre>@@ rather than
@@html:<pre>@@export SLA_DIR="​/var/blah​/"@@html:</pre>@@.

After install you can link to targets with headers such as
#+begin_src c++
  /* main.cpp */
  #include <coronium/coronium.hpp>
  #include <coronium/types.h>
  #include <coronium/loadimage.hh>
  #include <coronium/sleigh.hh>
  #include <coronium/emulate.hh>
  /* ... */  
#+end_src

via the cmdline -- =g++ main.cpp -lcoronium -o main=
